# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kernel2d <- function(x, y, h) {
    .Call('sparr_kernel2d', PACKAGE = 'sparr', x, y, h)
}

